export let CURSOS = [
    {
      nombre: "ARITMETICA",
      temas: ["RAZONES","PROPORCIONES","RAZONES GEOMETRICAS IGUALES","MAGNITUDES PROPORCIONALES","REGLA DE TRES",
            "PORCENTAJE","INTERES SIMPLE", "MEZCLA","ESTADISTICA","MEDIDAS DE TENDENCIA CENTRAL","INTRODUCCION AL ANALISIS COMBINATORIO",
          "PROBABILIDAD","NUMERACION","CONTEO DE NUMEROS Y CIFRAS","OPERACIONES","SUSTRACCION","MULTIPLICACION Y DIVISION",
        "OPERACIONES COMBINADAS","DIVISIBILIDAD","NUMEROS PRIMOS","POTENCIACION","RADICACION"]
    },
    {
      nombre: "ALGEBRA",
      temas: ["LOGICA Y CONJUNTOS","ECUACIONES E INECUACIONES","FUNCIONES","POLINOMIOS","FUNCION EXPONENCUAL Y LOGARITMICA",
              "MATRICES","DETERMINANTES","SISTEMA DE ECUACIONES","SISTEMA DE INECUACIONES","SUCESIONES Y PROGRESIONES"]
    },
    {
      nombre: "GEOMETRIA",
      temas: ["NOCIONES BASICAS","ANGULOS","TRIANGULOS","CONGRUENCIA DE TRIANGULOS","APLICACIONES DE LA CONGRUENCIA","POLIGONOS",
              "CUADRILATEROS","CIRCUNFERENCIA","PROPORCIONALIDAD","SEMEJANZA DE TRIANGULOS","RELACIONES METRICAS EN EL TRIANGULO RECTANGULO",
              "RELACIONES METRICAS EN EL TRIANGULO OBLICUANGULO","POLIGONOS REGUALRES","AREA DE UNA REGION TRIANGULAR",
            "RELACION DE AREAS TRIANGULARES","AREAS DE REGIONES TRAPEZOIDALES","AREAS DE REGIONES CIRCULARES","ELEMENTOS DE GEOMETRIA EN EL ESPACIO",
              "ANGULO DIEDRO","ANGULO POLIEDRO","POLIEDROS","PIRAMIDE","CILINDRO","CONO","SUPERFICIE ESFERICA","ESFERA"]
    },
    {
      nombre: "TRIGONOMETRIA",
      temas: ["ANGULO TRIGONOMETRICO","LONGITUD DE ARCO DE LA CIRCUNFERENCIA Y AREA DEL SECTOR CIRCULAR","RAZONES TRIGONOMETRICAS DE ANGULOS AGUDOS",
          "RAZONES TRIGONOMETRICAS DE ANGULOS DE CUALQUIER MAGNITUD","RAZONES TRIGONOMETRICAS EN LA CIRCUNFERENCIA TRIGONOMETRICA",
        "IDENTIDADES TRIGONOMETRICAS","FUNCIONES TRIGONOMETRICAS Y SUS GRAFICAS","FUNCIONES TRIGONOMETRICAS INVERSAS",
      "ECUACIONES E INECUACIONES TRIGONOMETRICAS","RESOLUCION DE TRIANGULOS"]
    },
    {
      nombre: "FISICA",
      temas: ["VECTORES","CINEMATICA","MRU","MRUV","MCU","ESTATICA","DINAMICA","TRABAJO Y ENERGIA","IMPULSO","MOVIMIENTO ARMONICO SIMPLE",
            "ESTATICA DE FLUIDOS","FISICA TERMICA","ELECTROSTATICA","CORRIENTE ELECTRICA","ELECTROMAGNETISMO","INDUCCION ELECTROMAGNETICA",
          "ONDAS ELECTROMAGNETICAS","OPTICA GEOMETRICA"]
    },
    {
      nombre: "QUIMICA",
      temas: ["MATERIA Y COMPOSICION","ESTRUCTURA ATOMICA","TABLA PERIODICA MODERNA","ENLACE QUIMICO","NOMENCLATURA DE COMPUESTOS INORGANICOS",
              "CANTIDAD DE SUSTANCIA","GASES","ESTEQUIOMETRIA","SOLUCIONES","INTRODUCCION A LA QUIMICA INORGANICA"]
    },
    {
      nombre: "RAZONAMIENTO MATEMATICO",
      temas: ["ANALISIS DE FIGURAS","RAZONAMIENTO LOGICO","SUCESIONES Y DISTRIBUCIONES NUMERICAS","SUFICIENCIA DE DATOS",
              "RAZONAMIENTO NUMERICO","OPERADORES","TABLAS Y GRAFICOS ESTADISTICOS"]
    },
    {
      nombre: "RAZONAMIENTO VERBAL",
      temas: ["DEFINICIONES","ANALOGIAS","PRECISION LEXICA EN CONTEXTO","ANTONIMIA CONTEXTUAL","CONECTORES LOGICOS-TEXTUALES",
              "INFORMACION ELIMINADA","PLAN DE REDACCION","INCLUSION DE ENUNCIADO","COHERENCIA Y COHESION TEXTUAL","COMPRESION DE LECTURA",]
    },
    {
      nombre: "COMUNICACION Y LENGUA",
      temas: ["LENGUAJES, LENGUA Y HABLA","LA ESCRITURA","LA SILABA Y LA ESTRUCTURA","LA ACENTUACION ORTOGRAFICA","LOS SIGNOS DE PUNTUACION EN LA ESCRITURA",
              "SIGNIFICADO DE LAS PALABRAS","ESTRUCTURA MORFOLOGIA DE LA PALABRA","NORMAS DE CORRECCION IDIOMATICA","EL VERBO",
              "LA PREPOSICION Y EL REGIMEN PREPOSICIONAL","LA ORACION SIMPLE","LA ORACION COMPUESTA","PROPOSICIONES SUBORDINADAS"]
    },
    {
      nombre: "LITERATURA",
      temas: ["TEORIA LITERARIA","LITERATURA GRIEGA","LITERATURA MEDIEVAL","RENACIMIENTO Y BARROCO","ROMANTICISMO","REALISMO",
              "NARRATIVA CONTEMPORANEA","LITERATURA MEDIEVAL ESPAÑOLA","EL SIGLO DE ORO","EL TEATRO DEL SIGLO DE ORO",
            "GENERACION DEL 98","GENERACION DEL 27","MODERNISMO","NUEVA NARRATIVA HISPANOAMERICANA","EL BOOM LATINOAMERICANO",
            "POESIA CONTEMPORANEA","LITERATURA PREHISPANICA","LITERATURA COLONIAL","LITERATURA DE LA EMANCIPACION","LITERATURA REPUBLICANA",
          "ROMANTICISMO","REALISMO","MODERNISMO","MOVIMIENTO COLONIDA","JOSE CARLOS MARIATEGUI","INDIGENISMO","GENERACION DEL 50",
            "LITERATURA ACTUAL","GENERACION DEL 70"]
    },
    {
      nombre: "HISTORIA DEL PERU Y DLE MUNDO",
      temas: ["EL PROCESO DE HOMONIZACION","POBLAMIENTO DE AMERICA","CULTURAS ANTIGUAS","ORIGEN Y FORMACION DE LA CULTURA ANDINA","INVASIONES BARBARAS",
              "HORIZONTE TARDIO","EL RENACIMIENTO","DESTRUCCION DEL TAHUANTINSUYO","REVOLUCIONES BURGUESAS","REBELIONES INDIGENAS DEL SIGLO XVIII",
              "INDUSTRIALIZACION Y PREDOMINIO INGLES","SITUACION DEL PERU A INCIOS DE LA REPUBLICA","PERIODO ENTRE GUERRAS","REVOLUCION RUSA",
              "RECONSTRUCCION NACIONAL","LA GUERRA FRIA","REVOLUCION CHINA","AUTORITARISMO Y DEMOCRACIA","GLOBALIZACION Y NUEVO ORDEN ECONOMICO MUNDIAL",
              "RETORNO AL REGIMEN CONSTITUCIONAL"]
    },
    {
      nombre: "GEOGRAFIA Y DESARROLLO NACIONAL",
      temas: ["TEORIA GEOGRAFICA Y ELEMENTOS PARA LA LOCALIZACION","REPRESENTACION DEL ESPACIO GEOGRAFICO","ECOSISTEMAS","AREAS PROTEGIDAS DEL PERU",
              "GEOMORFOLOGIA DEL PERU","MAR PERUANO","AGUA COMO RECURSO DEL PERU","DIVISION DEL TERRITORIO PERUANO","ACTIVIDADES ECONOMICAS",
              "GEOGRAFIA HUMANA","DINAMICA POBLACIONAL Y SUS EFECTOS SOCIOCULTURALES","EL PERU EN EL CONTEXTO GEOPOLITICO","PERU Y LOS ACUERDOS DE INTEGRACION",
              "ESTADO PERUANO","EL PODER POLITICO Y LEGIMITZACION","ORGANIZADORES CIVILES","CONVIVENCIA EN EL PERU","LA DIVERSIDAD CULTURAL COMO PRINCIPAL RIQUEZA HEREDADA DE NUESTROS ANCESTROS"]
    },
    {
      nombre: "ECONOMIA",
      temas: ["DOCTRINAS ECONOMICAS","NECESIDADES HUMANAS","FACTORES PRODUCTIVOS","PROCESO ECNONOMICO","TEORIA DEL MERCADO",
              "MODELOS DEL MERCADO","TEORIA DE LA EMPRESA","SISTEMA MONETARIO","SISTEMA FINANCIERO","SECTOR PUBLICO","ROL ECONOMICO",
              "INDICADORES MACROECONOMICOS","CRECIMIENTO Y DESARROLLO","COMERCIO INTERNACIONAL","SISTEMA MONETARIO INTERNACIONAL",
              "ORGANISMOS FINANCIEROS INTERNACIONALES","INTEGRACION ECONOMICA"]
    },
    {
      nombre: "FILOSOFIA",
      temas: ["FILOSOFIA ANTIGUA I","FILOSOFIA ANTIGUA II","FILOSOFIA ANTIGUA III","FILOSOFIA MODERNA I","FILOSOFIA MODERNA II",
              "FILOSOFIA MODERNA III","FILOSOFIA CONTEMPORANEA I","FILOSOFIA CONTEMPORANEA II","FILOSOFIA CONTEMPORANEA III",
            "AXIOLOGIA","ETICA Y POLITICA","GNOSEOLOGIA I","GNOSEOLOGIA II","EPISTEMOLOGIA"]
    },
    {
      nombre: "LOGICA",
      temas: ["LOGICA I","LOGICA II","LOGICA III"]
    },
    {
      nombre: "PSICOLOGIA",
      temas: ["ORIGENES DE LA PSICOLOGIA","FACTORES BIOLOGICOS DEL COMPORTAMIENTO I","FACTORES BIOLOGICOS DEL COMPORTAMIENTO II",
              "EL PSICOANALISIS","PROCESOS COGNITIVOS","LA PERCEPCION","MEMORIA","IMAGINACION","LA INTELIGENCIA",
              "TEST PSICOLOGICOS","EL PROCESO DE APRENDIZAJE","PENSAMIENTO Y LENGUAJE","PERSONALIDAD","SEXUALIDAD","SALUD PSICOLOGICA"]
    }
  ]


